In [3]:
'''Problem Statement 1: Write a Python program to multiply a 𝑀 × 𝑁 matrix by 𝑁 × 𝐴 matrix and
create a real matrix product.
Example:
Input:
Enter value M: 5
Enter value N: 3
Enter value A: 2
'''

import numpy as np
a=np.random.random((5,3))
print ("First Array is: ",a)
b=np.random.random((3,2))
print("Second Array is: ",b)
c=np.dot(a,b)
print("Real Matrix Array is: ",c)


First Array is:  [[0.53394109 0.28574041 0.76230416]
 [0.69286227 0.5860017  0.75809988]
 [0.48290301 0.3495055  0.22582818]
 [0.80230774 0.77200124 0.8761462 ]
 [0.24716645 0.6193567  0.71132458]]
Second Array is:  [[0.76927028 0.53356072]
 [0.41426771 0.04758924]
 [0.37434009 0.92168432]]
Real Matrix Array is:  [[0.81447905 1.00109195]
 [1.05954711 1.09630024]
 [0.60080832 0.48243307]
 [1.26498333 1.27234906]
 [0.7129946  0.81696974]]


In [11]:
'''Problem statement 2: Write a NumPy program to check if each element of an array of your
choice is composed of digits, lower case letters, and upper case letters only.
Hint: You can use isdigit(),islower(), and isupper() function.
'''
import numpy as np
Original_Array = np.array(['PYTHON', 'PHP', 'JS', 'Examples', 'html5', '5'])
print("\nOriginal Array:")
print(Original_Array)
a = np.char.isdigit(x)
b = np.char.islower(x)
c = np.char.isupper(x)
print("Digits only : ", a)
print("Lower cases only : ", b)
print("Upper cases only : ", c)

# This pogram is running correctlyin visual basics


Original Array:
['PYTHON' 'PHP' 'JS' 'Examples' 'html5' '5']


NameError: name 'x' is not defined

In [13]:
'''Write a program that reads two space-separated positive integers 𝑋 and
𝑌 as input and perform the following tasks:
Tasks to be performed:
1. Create a list (lst1) starting at one (1) with 16 elements at a step of 𝑋
2. Create a list (lst2) starting at one (1) with 16 elements at a step of 𝑌
3. Create two NumPy arrays np1 and np2 using lst1 and lst2 respectively
4. Reshape both the NumPy arrays to (4,4)
5. Create a new np array (np3) with values obtained by subtracting both the arrays (np1 -
np2)
6. Print all the elements of np3 in a single dimension list like the format as shown below:
a. [n0 n1 n2 n3 n4 n5 n6 n7 n8]
'''

import numpy as np

# Step 1: Read input values
X, Y = map(int, input("Enter two space-separated positive integers X and Y: ").split())

# Step 2: Create lst1 and lst2
lst1 = list(range(1, 16 * X + 1, X))
lst2 = list(range(1, 16 * Y + 1, Y))

# Step 3: Create np1 and np2 using lst1 and lst2 respectively
np1 = np.array(lst1)
np2 = np.array(lst2)

# Step 4: Reshape both NumPy arrays to (4, 4)
np1 = np1.reshape((4, 4))
np2 = np2.reshape((4, 4))

# Step 5: Create np3 by subtracting np2 from np1
np3 = np1 - np2

# Step 6: Print the elements of np3 in a single-dimensional list format
np3_list = np3.flatten().tolist()
print(np3_list)


Enter two space-separated positive integers X and Y: 7 9
[0, -2, -4, -6, -8, -10, -12, -14, -16, -18, -20, -22, -24, -26, -28, -30]


In [15]:
'''Problem set 4
Write a Python program that takes two integer-NumPy arrays, 𝑃 and 𝑄 of
shape [3 ∗ 3] and perform the following task:
Task to be performed:
Print the element-wise difference of the matrix 𝑃 and 𝑄 (𝑃 − 𝑄).
'''

import numpy as np

# Step 1: Create two NumPy arrays P and Q of shape [3x3]
# You can either initialize them with your own values or read them from user input
# Here, we'll initialize them with example values for demonstration purposes
P = np.array([[23, 56, 87],
              [3, 6, 96],
              [4, 6, 78]])

Q = np.array([[12, 34, 54],
              [7, 2, 54],
              [6, 2, 78]])

# Step 2: Calculate the element-wise difference of P and Q (P - Q)
result = P - Q

# Step 3: Print the result
print("Element-wise difference of P and Q (P - Q):")
print(result)


Element-wise difference of P and Q (P - Q):
[[11 22 33]
 [-4  4 42]
 [-2  4  0]]
